name: crypto_tutorial
description: Proiect MDS
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  chart_sparkline: 1.0.13
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: 21.1.41
  syncfusion_flutter_core: 21.1.41
  cupertino_icons: ^1.0.5
<<<<<<< Updated upstream
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.4.2
=======
  firebase_auth: 4.6.0
  cloud_firestore: 4.7.0
  flutter_local_notifications: ^7.0.0
  rxdart: ^0.27.7
  workmanager: ^0.5.1
  flutter_html: ^2.1.0
  url_launcher: 6.0.10
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/icons/
     - assets/image/